name: abma
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.1.2
  - numpy=1.24.3
  - pandas=2.0.2
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyterlab=4.0.2
  - jupyter=1.0.0
  - ipywidgets=8.0.6
  - networkx=3.1
  - scikit-learn=1.2.2
  - statsmodels=0.14.0
  - tornado=6.3.2
  - bokeh=3.1.1
  - plotly=5.15.0
  - pip:
    - mesa==1.2.1
    # mesa-geo removed to avoid version conflict
    - pyarrow==12.0.1
    - xlrd==2.0.1
    - openpyxl==3.1.2
    - tabulate==0.9.0
    - graphviz==0.20.1